import dotenv
from google import genai
from common.llm_test_generator import LLMTestGenerator
from common.prompt_generator import PromptGenerator
from common.abstract_executor import AbstractExecutor
from file_name_check import file_name_check
from to_test.number_to_words import number_to_words
from to_test.strong_password_checker import strong_password_checker
import importlib
import os
from fuzzing_generator import FuzzingGenerator

dotenv.load_dotenv()

key = os.getenv("API_KEY")

def generate_inital_tests_with_llm(client, model_name, function_to_test):
    # Create an LLMTestGenerator object with the generative model and the function to test
    llm_generator = LLMTestGenerator(client, model_name=model_name, function=function_to_test)

    # Create a PromptGenerator object with the function to test
    prompt_generator = PromptGenerator(function_to_test)

    # Generate a prompt for the function
    prompt = prompt_generator.generate_prompt()

    # Print the prompt
    print(prompt)

    # Create a test function using the LLMTestGenerator
    test, test_name = llm_generator.create_test_function(prompt)

    print("Tests produced by LLM:")

    print(test)

    # Define the filename for the generated test file
    filename = "test_generated.py"

    # Write the test function to the file
    llm_generator.write_test_to_file(test, filename=filename)

    # Get the module name and function name from the filename
    module_name = filename.split(".")[0]
    function_name = test_name

    # Import the module dynamically
    module = importlib.import_module(module_name)

    # Get the function from the module
    function = getattr(module, function_name)

    executor = AbstractExecutor(function)

    # Execute the input function and get the coverage date
    coverage_data = executor._execute_input(input=function_to_test)


    # Print the coverage date
    # return function, coverage_data
    return test, function, coverage_data
    

if __name__ == "__main__":
    # Configure the generative AI with the API key
    client = genai.Client(api_key=key)

    # Create a generative model
    model_name = "gemini-2.5-flash"

    function_to_test = number_to_words #file_name_check
    #function_to_test = strong_password_checker

    # Fitness function weights: Fitness = (alpha * line_coverage) + (beta * branch_coverage) - (gamma * num_tests)
    alpha = 1.0    # Weight for line coverage
    beta = 1.0     # Weight for branch coverage
    gamma = 0.05   # Penalty for test count
    mutation_budget = 100  # Number of mutation iterations

    ######Generate intial tests with LLM

    # Before generating test if code is already present
    if not os.path.exists("test_generated.py"):
        test_code, test_function, coverage_data = generate_inital_tests_with_llm(client, model_name, function_to_test)
    else:
        # If the test code is already present, import it and execute to get coverage data
        module = importlib.import_module("test_generated")
        
        # Find the test function by looking for functions in the module
        test_function = None
        for attr_name in dir(module):
            if attr_name.startswith("test_") and callable(getattr(module, attr_name)):
                test_function = getattr(module, attr_name)
                break
        
        if test_function is None:
            raise ValueError("No test function found in test_generated.py")
        
        executor = AbstractExecutor(test_function)
        coverage_data = executor._execute_input(input=function_to_test)
        with open("test_generated.py", "r") as f:
            test_code = f.read()
    # test, coverage_data = generate_inital_tests_with_llm(client, model_name, function_to_test)
    
    initial_coverage = coverage_data

    # define the executor to be used with your test generator
    executor = AbstractExecutor(function_to_test)

    # try:

    #     """
    #     TODO:
    #     -Insert your code here to improve the initial line and branch coverage
    #     -Use the "test" returned from the generate_inital_tests_with_llm function to start your generation
    #     -You can leverage the information about the datatype from the inputs in "test" generated by the LLM
    #     -You must use the "executor" to evaluate your tests and guide the generation process
    #     -Your test generator shoud return a list with new inputs to be evaluated
    #     -You goal is to keep the number of inputs as small as possible and the coverage as high as possible
    #     """
        
    #     generator = FuzzingGenerator(function_to_test, test, initial_coverage, executor)
    #     seed_pool = generator._seed_pool()
    #     new_inputs_list = generator.mutate_list(seed_pool, alpha=alpha, beta=beta, gamma=gamma, budget=mutation_budget)
    # except Exception as e:
    #     print(f"Exception occured: {e}")
    generator = FuzzingGenerator(function_to_test, test_code, initial_coverage, executor)
    seed_pool = generator._seed_pool()
    new_inputs_list = generator.mutate_list(seed_pool, alpha=alpha, beta=beta, gamma=gamma, budget=mutation_budget)
    print(f"New inputs generated: {new_inputs_list}")
    coverage_data = executor._execute_input(input_list=new_inputs_list[0])

    print(initial_coverage)
    print(coverage_data)
    
    line_coverage_improment = coverage_data["coverage"]["percent_covered"] - initial_coverage["coverage"]["percent_covered"]
    branch_coverage_improment = coverage_data["coverage"]["covered_branches"]/coverage_data["coverage"]["num_branches"] - initial_coverage["coverage"]["covered_branches"]/initial_coverage["coverage"]["num_branches"]
    total_tests = len(new_inputs_list)
    final_score = (line_coverage_improment + branch_coverage_improment) / total_tests
    print(f"Final score: {final_score}")

    




    