def test_number_to_words(number_to_words):
    assert number_to_words(0) == "Zero"
    assert number_to_words(1) == "One"
    assert number_to_words(9) == "Nine"
    assert number_to_words(10) == "Ten"
    assert number_to_words(12) == "Twelve"
    assert number_to_words(19) == "Nineteen"
    assert number_to_words(20) == "Twenty"
    assert number_to_words(21) == "Twenty One"
    assert number_to_words(50) == "Fifty"
    assert number_to_words(99) == "Ninety Nine"
    assert number_to_words(100) == "One Hundred"
    assert number_to_words(101) == "One Hundred One"
    assert number_to_words(123) == "One Hundred Twenty Three"
    assert number_to_words(500) == "Five Hundred"
    assert number_to_words(789) == "Seven Hundred Eighty Nine"
    assert number_to_words(999) == "Nine Hundred Ninety Nine"
    assert number_to_words(1000) == "One Thousand"
    assert number_to_words(1001) == "One Thousand One"
    assert number_to_words(1010) == "One Thousand Ten"
    assert number_to_words(1100) == "One Thousand One Hundred"
    assert number_to_words(1234) == "One Thousand Two Hundred Thirty Four"
    assert number_to_words(10000) == "Ten Thousand"
    assert number_to_words(10001) == "Ten Thousand One"
    assert number_to_words(23456) == "Twenty Three Thousand Four Hundred Fifty Six"
    assert number_to_words(100000) == "One Hundred Thousand"
    assert number_to_words(100001) == "One Hundred Thousand One"
    assert number_to_words(999999) == "Nine Hundred Ninety Nine Thousand Nine Hundred Ninety Nine"
    assert number_to_words(1000000) == "One Million"
    assert number_to_words(1000001) == "One Million One"
    assert number_to_words(1000100) == "One Million One Hundred"
    assert number_to_words(1001000) == "One Million One Thousand"
    assert number_to_words(1234567) == "One Million Two Hundred Thirty Four Thousand Five Hundred Sixty Seven"
    assert number_to_words(7000000) == "Seven Million"
    assert number_to_words(123000000) == "One Hundred Twenty Three Million"
    assert number_to_words(987654321) == "Nine Hundred Eighty Seven Million Six Hundred Fifty Four Thousand Three Hundred Twenty One"
    assert number_to_words(1000000000) == "One Billion"
    assert number_to_words(1000000001) == "One Billion One"
    assert number_to_words(1234567890) == "One Billion Two Hundred Thirty Four Million Five Hundred Sixty Seven Thousand Eight Hundred Ninety"
    assert number_to_words(50000000000) == "Fifty Billion"
    assert number_to_words(1234567890123) == "One Trillion Two Hundred Thirty Four Billion Five Hundred Sixty Seven Million Eight Hundred Ninety Thousand One Hundred Twenty Three"
    assert number_to_words(1000000100) == "One Billion One Hundred"
    assert number_to_words(1000001000) == "One Billion One Thousand"
    assert number_to_words(1000010000) == "One Billion Ten Thousand"
    assert number_to_words(1000100000) == "One Billion One Hundred Thousand"
    assert number_to_words(2147483647) == "Two Billion One Hundred Forty Seven Million Four Hundred Eighty Three Thousand Six Hundred Forty Seven"
    assert number_to_words(501) == "Five Hundred One"
    assert number_to_words(500001) == "Five Hundred Thousand One"
    assert number_to_words(10501) == "Ten Thousand Five Hundred One"
    assert number_to_words(1000000000000) == "One Trillion"
    assert number_to_words(1000000001000) == "One Trillion One Thousand"
    assert number_to_words(1000000000001) == "One Trillion One"
    assert number_to_words(1000001000000) == "One Trillion One Million"
